### PR TITLE
DonNan 

### PR DESCRIPTION
**Pull request by DonNanNut**
* DonNan Dai -- [Acrostic Poem](http://wp.nyu.edu/tischschoolofthearts-donnan/2020/09/15/a2z-homework-1/)

### CODE REVIEW

**Comment by DonNanNut** [comment]
* DonNan Dai -- [Acrostic Poem](http://wp.nyu.edu/tischschoolofthearts-donnan/2020/09/15/a2z-homework-1/)

**Comment by DonNanNut** [comment]
test

**Comment by shiffman** [comment]
Hi @DonNanNut! I think something got wonky with this pull request, can you try re-submitting? I can add your link directly if you prefer!

**Comment by DonNanNut** [comment]
Hi Daniel,

sorry I had not checked my email for the thread. I have my comment like the
following:

   - DonNan Dai -- Acrostic Poem
   <http://wp.nyu.edu/tischschoolofthearts-donnan/2020/09/15/a2z-homework-1/>


Thanks for the update!

**Comment by DonNanNut** [comment]
DonNan Dai -- Acrostic Poem ( link: https://wp.nyu.edu/tischschoolofthearts-donnan/2020/09/15/a2z-homework-1/ )

**Comment by DonNanNut** [comment]
Should I leave the pull request open or close it instead?

**Comment by shiffman** [comment]
I'll close it and add the link manually! I think maybe by accident the changes are being pull requested to the incorrect branch. I'm not sure!

Screen Shot 2020-09-21 at 10 36 43 PM

**Pull request closed without merging**
